// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6AF6pCmp2voH9DflGf6G12My_RByPYeQ',
    appId: '1:587792224504:web:fcdab17cafb523034b6b0d',
    messagingSenderId: '587792224504',
    projectId: 'todofirebaseflutter-caf01',
    authDomain: 'todofirebaseflutter-caf01.firebaseapp.com',
    storageBucket: 'todofirebaseflutter-caf01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvIG_2_Wg6dBC5WLxI4ra0OvMrqMfLpHM',
    appId: '1:587792224504:android:6f93028692cf1c794b6b0d',
    messagingSenderId: '587792224504',
    projectId: 'todofirebaseflutter-caf01',
    storageBucket: 'todofirebaseflutter-caf01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsx6eX6ZvHCkMRRTq4DfKskFL2nC8G-2I',
    appId: '1:587792224504:ios:e2be21a75e0825504b6b0d',
    messagingSenderId: '587792224504',
    projectId: 'todofirebaseflutter-caf01',
    storageBucket: 'todofirebaseflutter-caf01.appspot.com',
    iosClientId: '587792224504-5aqtj9kbov37upq4kl3ancnutp5nf23o.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsx6eX6ZvHCkMRRTq4DfKskFL2nC8G-2I',
    appId: '1:587792224504:ios:e2be21a75e0825504b6b0d',
    messagingSenderId: '587792224504',
    projectId: 'todofirebaseflutter-caf01',
    storageBucket: 'todofirebaseflutter-caf01.appspot.com',
    iosClientId: '587792224504-5aqtj9kbov37upq4kl3ancnutp5nf23o.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoFirebaseFlutter',
  );
}
